# Generated by Django 2.0.1 on 2018-02-05 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DECTHandset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='Description')),
                ('enableEncryption', models.BooleanField(verbose_name='Use encrypted DECT')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Event name')),
                ('location', models.CharField(max_length=128, verbose_name='Event location')),
                ('eventStreamTarget', models.CharField(max_length=256, verbose_name='PBX events target')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('registrationStart', models.DateField(blank=True, null=True, verbose_name='Registration start date')),
                ('extensionLength', models.PositiveIntegerField(verbose_name='Extension length (in number of digits)')),
                ('extensionStart', models.CharField(max_length=32, verbose_name='Extension start')),
                ('extensionEnd', models.CharField(max_length=32, verbose_name='Extension end')),
                ('orgaExtensionStart', models.CharField(max_length=32, verbose_name='Orga Extension start')),
                ('orgaExtensionEnd', models.CharField(max_length=32, verbose_name='Orga Extension end')),
                ('hasGSM', models.BooleanField(verbose_name='This event has also a GSM network')),
                ('descriptionDE', models.TextField(verbose_name='Event description (German)')),
                ('descriptionEN', models.TextField(verbose_name='Event description (English)')),
                ('url', models.URLField(verbose_name='Event Homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastChanged', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('type', models.CharField(choices=[('SIP', 'SIP telephone'), ('DECT', 'DECT handset'), ('GSM', 'GSM handset')], max_length=16, verbose_name='Type')),
                ('extension', models.CharField(max_length=32, verbose_name='Extension')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('inPhonebook', models.BooleanField(verbose_name='Show in public phonebook')),
                ('isInstalled', models.BooleanField(editable=False, verbose_name='Is installed?')),
                ('location', models.CharField(blank=True, max_length=64, verbose_name='Location')),
                ('registerToken', models.CharField(blank=True, editable=False, max_length=32, verbose_name='Selfregistration token')),
                ('displayModus', models.CharField(choices=[('NUMBER', 'Show only caller number'), ('NUMBER_NAME', 'Show caller number followed by name'), ('NAME', 'Show only caller name (if available)')], max_length=16, verbose_name='Display modus')),
                ('sipPassword', models.CharField(editable=False, max_length=16, verbose_name='SIP password')),
                ('isPremium', models.BooleanField(verbose_name='Provision on premium server')),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
                ('handset', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DECTHandset')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
