# Generated by Django 2.0.1 on 2018-02-25 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_extension_useencryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Event timestamp')),
                ('delivered', models.BooleanField(default=False, verbose_name='Already delivered')),
                ('type', models.CharField(max_length=16, verbose_name='Event type')),
                ('data', models.TextField(verbose_name='Event data')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event', verbose_name='For event')),
            ],
        ),
        migrations.AlterField(
            model_name='extension',
            name='isInstalled',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is installed?'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='lastChanged',
            field=models.DateTimeField(editable=False, verbose_name='Last changed'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extension',
            name='type',
            field=models.CharField(choices=[('SIP', 'SIP telephone'), ('DECT', 'DECT handset'), ('GSM', 'GSM handset'), ('GROUP', 'Callgroup')], max_length=16, verbose_name='Type'),
        ),
    ]
