# Generated by Django 2.0.1 on 2018-02-25 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180225_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='inPhonebook',
            field=models.BooleanField(default=True, verbose_name='Show in public phonebook'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='isPremium',
            field=models.BooleanField(default=False, verbose_name='Provision on premium server'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extension',
            name='useEncryption',
            field=models.BooleanField(default=False, verbose_name='Use encryption'),
        ),
        migrations.AlterUniqueTogether(
            name='extension',
            unique_together={('event', 'registerToken')},
        ),
    ]
