# Generated by Django 2.0.1 on 2018-02-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180225_2050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extension',
            unique_together=set(),
        ),
    ]
