# Generated by Django 2.0.1 on 2018-03-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180306_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='type',
            field=models.CharField(choices=[('SIP', 'SIP telephone'), ('DECT', 'DECT handset'), ('GSM', 'GSM handset'), ('GROUP', 'Callgroup'), ('SPECIAL', 'Special extension')], max_length=16, verbose_name='Type'),
        ),
    ]
