# Generated by Django 2.0.1 on 2018-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180306_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='displayModus',
            field=models.CharField(choices=[('NUMBER', 'Show only caller number'), ('NUMBER_NAME', 'Show caller number followed by name'), ('NAME', 'Show only caller name (if available)')], default='NUMBER_NAME', max_length=16, verbose_name='Display modus'),
        ),
    ]
