# Generated by Django 2.0.3 on 2018-03-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='lastChanged',
            field=models.DateTimeField(auto_now=True, verbose_name='Last changed'),
        ),
    ]
