# Generated by Django 2.0.3 on 2018-03-26 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_add_auto_now_to_lastChanged'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='CallGroup Admins')),
                ('callgroup_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callgroup_extension', to='core.Extension', verbose_name='Callgroup Extension')),
            ],
        ),
        migrations.CreateModel(
            name='CallGroupInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(blank=True, max_length=64)),
                ('accepted', models.BooleanField(default=False)),
                ('callgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CallGroup')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Extension')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callgroup_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='callgroup',
            name='extensions',
            field=models.ManyToManyField(related_name='called_extensions', through='core.CallGroupInvite', to='core.Extension'),
        ),
    ]
