# Generated by Django 2.0.8 on 2018-08-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_extension_announcement_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Description')),
                ('barcode', models.CharField(max_length=32, verbose_name='Barcode')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('serialNumber', models.CharField(blank=True, max_length=64, verbose_name='Serial number')),
                ('mac', models.CharField(blank=True, max_length=64, verbose_name='MAC address')),
                ('decommissioned', models.BooleanField(verbose_name='This item is decommissioned')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outDate', models.DateTimeField(auto_now_add=True, verbose_name='Lending start')),
                ('backDate', models.DateTimeField(blank=True, null=True, verbose_name='Lending end')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('lender', models.CharField(max_length=64, verbose_name='Lender')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Type name')),
                ('magic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Magic type that should happen for this inventory item')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='announcement_lang',
            field=models.CharField(choices=[('de-DE', 'Deutsch (Deutschland)'), ('en-GB', 'English (GB)'), ('en-US', 'English (US)')], default='DE-DE', max_length=5, verbose_name='Default Extension Announcement Language'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='announcement_lang',
            field=models.CharField(choices=[('de-DE', 'Deutsch (Deutschland)'), ('en-GB', 'English (GB)'), ('en-US', 'English (US)')], default='DE-DE', max_length=5, verbose_name='Announcement Language'),
        ),
        migrations.AddField(
            model_name='inventorylend',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='inventorylend',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Extension', verbose_name='Linked Extension'),
        ),
        migrations.AddField(
            model_name='inventorylend',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InventoryItem', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='itemType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.InventoryType', verbose_name='Type'),
        ),
    ]
