# Generated by Django 2.0.8 on 2018-08-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180820_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callgroup',
            name='callgroup_extension',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callgroup_extension', to='core.Extension', verbose_name='Callgroup Extension'),
        ),
        migrations.AlterField(
            model_name='callgroup',
            name='extensions',
            field=models.ManyToManyField(related_name='grouped_extensions', through='core.CallGroupInvite', to='core.Extension'),
        ),
    ]
