# Generated by Django 2.0.8 on 2018-10-14 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20180823_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=32, verbose_name='Extension')),
                ('valid_until', models.DateField(verbose_name='Claim valid until')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Alphanumeric claim token.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='extensionclaim',
            index=models.Index(fields=['token'], name='core_extens_token_848840_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='extensionclaim',
            unique_together={('event', 'extension')},
        ),
    ]
