# Generated by Django 2.0.8 on 2018-12-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181130_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionPool',
            fields=[
                ('extension', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Extension')),
            ],
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to='audio/', verbose_name='Audio File (<=1MB)'),
        ),
    ]
