# Generated by Django 2.0.8 on 2018-12-04 20:55

from django.db import migrations

def create_pool(apps, schema_editor):
    ExtensionPool = apps.get_model("core", "ExtensionPool")
    db_alias = schema_editor.connection.alias
    for x in range(10000):
        entry = ExtensionPool(extension=str(x))
        entry.save()

def empty_pool(apps, schema_editor):
    ExtensionPool = apps.get_model("core", "ExtensionPool")
    ExtensionPool.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_create_extensionpool'),
    ]

    operations = [
        migrations.RunPython(create_pool, empty_pool),
    ]
