# Generated by Django 2.0.9 on 2018-12-15 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_seed_extensionpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(editable=False, related_name='organizedEvents', to=settings.AUTH_USER_MODEL, verbose_name='Organizers of this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='pocHelpdesk',
            field=models.ManyToManyField(editable=False, related_name='helpdeskEvents', to=settings.AUTH_USER_MODEL, verbose_name='PoC helpdesk people in this event'),
        ),
    ]
