# Generated by Django 2.0.9 on 2018-12-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181215_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='threeGOptIn',
            field=models.BooleanField(default=False, help_text='Use 3G in addition to 2G mobile network (highly experimental). Voice might not work.', verbose_name='Use 3G'),
        ),
    ]
