# Generated by Django 2.1.5 on 2019-02-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190217_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decthandset',
            name='ipei',
            field=models.CharField(max_length=16, verbose_name='IPEI in ETSI 300 175-6 Annex C format'),
        ),
    ]
