# Generated by Django 2.1.5 on 2019-03-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190218_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='decthandset',
            name='vendor',
            field=models.CharField(blank=True, choices=[('MITEL', 'Aastra/DeTeWe/Mitel'), ('AEG', 'AEG'), ('ALCATEL', 'Alcatel'), ('AVAYA', 'Avaya'), ('AVM', 'AVM'), ('BT', 'BT'), ('CISCO', 'Cisco'), ('COCOON', 'Cocoon'), ('GIGASET', 'Gigaset'), ('GRANDSTREAM', 'Grandstream'), ('GRUNDIG', 'Grundig'), ('MEDION', 'Medion'), ('MOTOROLA', 'Motorola'), ('ORCHID', 'Orchid'), ('PANASONIC', 'Panasonic'), ('PENTATECH', 'Pentatec'), ('PHILIPS', 'Philips'), ('PLANTRONICS', 'Plantronics'), ('POLYCOM', 'Polycom'), ('PROFOON', 'Profoon'), ('SNOM', 'Snom'), ('SWISSCOM', 'Swisscom'), ('SWISSVOICE', 'Swissvoice'), ('TELEKOM', 'Telekom'), ('TOPCOM', 'Topcom'), ('UNIFY', 'Unify'), ('YEALINK', 'Yealink')], help_text='Help us to create an IPEI to vendor translation table and select the vendor of your device from the list. If the vendor is missing, please create a ticket in our support system (support.eventphone.de). Thanks :)', max_length=32, verbose_name='Device vendor'),
        ),
        migrations.AlterField(
            model_name='decthandset',
            name='uak',
            field=models.CharField(editable=False, max_length=128, verbose_name='hex encoded UAK'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='handset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DECTHandset'),
        ),
    ]
