# Generated by Django 2.1.5 on 2019-03-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190324_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='DECTManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64, verbose_name='Manufacturer name')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='decthandset',
            name='vendor',
        ),
        migrations.AddField(
            model_name='decthandset',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Help us to create an IPEI to vendor translation table and select the vendor of your device from the list. If the vendor is missing, please create a ticket in our support system (support.eventphone.de). Thanks :)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DECTManufacturer', verbose_name='Device vendor'),
        ),
    ]
