# Generated by Django 2.1.5 on 2019-03-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190325_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='decthandset',
            name='model_designation',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Model designation'),
        ),
    ]
