# Generated by Django 2.1.5 on 2019-03-31 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_decthandset_model_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DECTInventorySuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Extension', verbose_name='Extension used in rent')),
            ],
        ),
        migrations.AlterField(
            model_name='decthandset',
            name='model_designation',
            field=models.CharField(blank=True, default='', help_text='Helps us to better understand manufacturer codes of devices.', max_length=32, verbose_name='Model designation'),
        ),
        migrations.AlterField(
            model_name='decthandset',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Help us to create an IPEI to vendor translation table and select the vendor of your device from the list. If the vendor is missing, please create a ticket in our <a href="/support" target="_blank">support system.</a> Thanks :)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DECTManufacturer', verbose_name='Device vendor'),
        ),
        migrations.AddField(
            model_name='dectinventorysuggestion',
            name='handset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DECTHandset', verbose_name='Handset'),
        ),
        migrations.AddField(
            model_name='dectinventorysuggestion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InventoryItem', verbose_name='Inventory item'),
        ),
    ]
