# Generated by Django 2.1.5 on 2019-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190331_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isPermanent',
        ),
        migrations.AddField(
            model_name='event',
            name='isPermanentAndPublic',
            field=models.BooleanField(default=False, verbose_name='This event is an event that is public although it is permanent'),
        ),
    ]
