# Generated by Django 2.1.5 on 2019-07-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190509_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='regularSipServer',
            field=models.CharField(default='voip.eventphone.de', max_length=128, verbose_name='(regular) SIP server address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='isPermanentAndPublic',
            field=models.BooleanField(default=False, verbose_name='This event is public although it is permanent'),
        ),
    ]
