# Generated by Django 2.1.5 on 2019-07-23 17:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190718_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='orgaKey',
            field=models.CharField(default=core.models._generate_orgakey, editable=False, max_length=64, verbose_name='Organizer key for this event'),
        ),
        migrations.AddField(
            model_name='extension',
            name='apply_for_rental_device',
            field=models.BooleanField(default=False, help_text='Check this box if you would like to receive a rental device for this extension on the event. Please note that we might need to prioritize if there are more applications than available rental devices.', verbose_name='Apply for rentral device'),
        ),
        migrations.AddField(
            model_name='extension',
            name='qualifies_for_rental_device',
            field=models.BooleanField(default=False, verbose_name='This extension may apply for a rental device.'),
        ),
    ]
