# Generated by Django 2.1.8 on 2019-08-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_manual_20190723'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='fourGOptIn',
            field=models.BooleanField(default=False, help_text='Use 4G access technology (very new, even more experimental, your phone might explode ;)', verbose_name='Use LTE/4G'),
        ),
        migrations.AddField(
            model_name='extension',
            name='twoGOptIn',
            field=models.BooleanField(default=True, help_text='Use 2G mobile network. This is the most stable technology and recommended to beused.', verbose_name='Use GSM/2G'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='threeGOptIn',
            field=models.BooleanField(default=False, help_text='Use 3G access access technology  (highly experimental). Voice might not work.', verbose_name='Use UMTS/3G'),
        ),
    ]
