# Generated by Django 2.1.5 on 2019-10-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_inventorytype_auto_recall'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalDeviceClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Rental device class name')),
            ],
        ),
        migrations.AddField(
            model_name='inventorytype',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.RentalDeviceClassification', verbose_name='Rental device class'),
        ),
    ]
