# Generated by Django 2.1.14 on 2019-12-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20191013_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentaldeviceclassification',
            options={'ordering': ['name']},
        ),
    ]
