# Generated by Django 2.1.14 on 2020-03-12 22:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20191210_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to=core.models.upload_file_name, verbose_name='Audio File (<=1MB)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='announcement_lang',
            field=models.CharField(choices=[('de-DE', 'Deutsch (Deutschland)'), ('en-GB', 'English (GB)'), ('en-US', 'English (US)')], default='de-DE', max_length=5, verbose_name='Default Extension Announcement Language'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='announcement_lang',
            field=models.CharField(choices=[('de-DE', 'Deutsch (Deutschland)'), ('en-GB', 'English (GB)'), ('en-US', 'English (US)')], default='de-DE', max_length=5, verbose_name='Announcement Language'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='fourGOptIn',
            field=models.BooleanField(default=False, help_text='Use 4G access technology (very new, even more experimental, your phone will explode ;)', verbose_name='Use LTE/4G'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='threeGOptIn',
            field=models.BooleanField(default=True, help_text='Use 3G access access technology  (highly experimental). Voice might not work.', verbose_name='Use UMTS/3G'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='twoGOptIn',
            field=models.BooleanField(default=True, help_text='Use 2G mobile network. This is the most stable technology and recommended to be used.', verbose_name='Use GSM/2G'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='type',
            field=models.CharField(choices=[('SIP', 'SIP telephone'), ('DECT', 'DECT handset'), ('GSM', 'GSM handset'), ('GROUP', 'Callgroup'), ('APP', 'Application'), ('SPECIAL', 'Special extension')], max_length=16, verbose_name='Type'),
        ),
    ]
