# Generated by Django 2.1.14 on 2020-03-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200312_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiremessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event timestamp'),
        ),
    ]
