# Generated by Django 2.1.14 on 2020-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200321_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiremessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Event timestamp'),
        ),
    ]
