# Generated by Django 2.1.14 on 2020-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200321_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='allow_dialout',
            field=models.BooleanField(default=False, verbose_name='Allow dialout'),
        ),
        migrations.AddField(
            model_name='extension',
            name='call_waiting',
            field=models.BooleanField(default=True, help_text='When this extension is currently on a call and another call arrives, the other call is NOT indicated that you are busy but normally ringing. The other call is signaled to the extension. This is usually nicely integrated with desktop SIP phones and works also with some DECT phones. If you want to signal busy to the other end when you are on a call, disable call waiting here.', verbose_name='Activate call waiting'),
        ),
    ]
