# Generated by Django 2.1.14 on 2020-04-11 11:19

from django.conf import settings
from django.db import migrations, models, transaction
import django.db.models.deletion


def callgroup_migration_function(apps, schema_editor):
    print("Starting manual migration of CallGroups")
    CallGroupInvite = apps.get_model("core", "CallGroupInvite")
    CallGroup = apps.get_model("core", "CallGroup")

    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        # remap all invites to be owned by the extensions now
        for invite in CallGroupInvite.objects.using(db_alias).all().select_related("callgroup"):
            invite.group = invite.callgroup.callgroup_extension
            invite.save()

        # move over all admins
        groups = CallGroup.objects.using(db_alias).all().select_related("callgroup_extension")
        for group in groups:
            for admin in group.admins.all():
                group.callgroup_extension.group_admins.add(admin)
            group.callgroup_extension.save()

    print("Manual migration of CallGroups done")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0042_auto_20200410_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='callgroupinvite',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Extension'),
        ),
        migrations.AddField(
            model_name='extension',
            name='group_admins',
            field=models.ManyToManyField(related_name='adminstrated_callgroups', to=settings.AUTH_USER_MODEL, verbose_name='Callgroup administrators'),
        ),
        migrations.AddField(
            model_name='extension',
            name='group_members',
            field=models.ManyToManyField(related_name='callgroups', through='core.CallGroupInvite', to='core.Extension'),
        ),
        migrations.AlterField(
            model_name='callgroupinvite',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callgroup_memberships', to='core.Extension'),
        ),
        migrations.AlterField(
            model_name='callgroupinvite',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callgroup_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(callgroup_migration_function),
        migrations.RemoveField(
            model_name='callgroup',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='callgroup',
            name='callgroup_extension',
        ),
        migrations.RemoveField(
            model_name='callgroup',
            name='extensions',
        ),
        migrations.RemoveField(
            model_name='callgroupinvite',
            name='callgroup',
        ),
        migrations.DeleteModel(
            name='CallGroup',
        ),
        migrations.AlterField(
            model_name='callgroupinvite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Extension'),
        ),
    ]
