# Generated by Django 2.1.14 on 2020-04-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_group_migration_20200411_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='callgroupinvite',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='callgroupinvite',
            name='delay_s',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
