# Generated by Django 2.1.14 on 2020-04-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200411_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='group_shortcode',
            field=models.CharField(blank=True, help_text='When a group call arrives, this short code will be shown in square brackets in front of the caller so that you can see that this a group call and which group it is coming from.', max_length=3, verbose_name='Group shortcode'),
        ),
    ]
