# Generated by Django 2.1.14 on 2020-04-14 23:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_extension_group_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mgr_key',
            field=models.CharField(default=core.models._generate_mgr_key, editable=False, max_length=64, verbose_name='Api Key'),
        ),
    ]
