# Generated by Django 2.1.14 on 2020-04-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_event_mgr_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mgr_key',
            field=models.CharField(default='INVALID_KEY', editable=False, max_length=150, verbose_name='Api Key'),
        ),
    ]
