# Generated by Django 2.1.14 on 2020-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200419_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiremessage',
            name='type',
            field=models.CharField(max_length=32, verbose_name='Event type'),
        ),
    ]
