# Generated by Django 2.1.14 on 2020-04-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_callgroupinvite_unique_index_20200426_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='sip_trunk',
            field=models.BooleanField(default=False, verbose_name='Configure this extension as trunk'),
        ),
    ]
