# Generated by Django 2.1.14 on 2020-04-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_extension_sip_trunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hasApp',
            field=models.BooleanField(default=True, verbose_name='This event has Applications.'),
        ),
        migrations.AddField(
            model_name='event',
            name='hasDECT',
            field=models.BooleanField(default=True, verbose_name='This event has DECT.'),
        ),
        migrations.AddField(
            model_name='event',
            name='hasPremium',
            field=models.BooleanField(default=False, verbose_name='This event has premium SIP.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hasGSM',
            field=models.BooleanField(default=False, verbose_name='This event has also a GSM network'),
        ),
    ]
