# Generated by Django 2.1.14 on 2020-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200426_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hasApp',
            field=models.BooleanField(default=True, verbose_name='This event has Applications'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hasDECT',
            field=models.BooleanField(default=True, verbose_name='This event has DECT'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hasPremium',
            field=models.BooleanField(default=False, verbose_name='This event has premium SIP'),
        ),
    ]
