# Generated by Garwin

from django.db import migrations, models


def mark_old_ringback_processed(apps, schema_editor):
    AudioFile = apps.get_model("core", "AudioFile")
    AudioFile.objects.using(schema_editor.connection.alias).all().update(processed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20200502_1259'),
    ]

    operations = [
        migrations.RunPython(mark_old_ringback_processed),
    ]
