# Generated by Django 3.0.5 on 2020-05-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200415_2236'),
        ('core', '0057_old_ringback_are_converted__20200502_1713'),
    ]

    operations = [
    ]
