# Generated by Django 3.0.5 on 2020-05-03 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_extensionclaim_mail_sent'),
        ('core', '0058_merge_20200502_1536'),
    ]

    operations = [
    ]
