# Generated by Django 3.0.6 on 2020-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_merge_20200503_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='extension',
            field=models.CharField(help_text='You can enter characters here, which will be automagically converted into their vanity digits upon save.', max_length=32, verbose_name='Extension'),
        ),
    ]
