# Generated by Django 3.0.5 on 2020-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200505_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='extension',
            field=models.CharField(help_text='You can enter characters here, which will be automagically converted into their vanity digits.', max_length=32, verbose_name='Extension'),
        ),
    ]
