# Generated by Django 3.0.11 on 2020-12-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200801_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='announcement_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_extensions', to='core.AudioFile', verbose_name='Announcement Audio'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='type',
            field=models.CharField(choices=[('SIP', 'SIP telephone'), ('DECT', 'DECT handset'), ('GSM', 'GSM handset'), ('GROUP', 'Callgroup'), ('APP', 'Application'), ('ANNOUNCEMENT', 'Announcement'), ('SPECIAL', 'Special extension')], max_length=16, verbose_name='Type'),
        ),
    ]
