# Generated by Django 3.0.14 on 2022-05-27 22:53

import core.models
from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20201220_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Berlin', use_pytz=False, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to=core.models.upload_file_name, verbose_name='Audio File (<=5MB)'),
        ),
    ]
