# Generated by Django 4.0.10 on 2023-10-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_audiofile_id_alter_callgroupinvite_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='direct_routing_target',
            field=models.CharField(blank=True, help_text='Optional routing target that should be invoked by yate when calling this special number. Calls are routed to the application, then stage2 routing invokes this routng target. Leave empty if call routing is already handled, e.g., via regexroute.', max_length=256, verbose_name='Yate direct routing target'),
        ),
    ]
