# Generated by Django 4.0.10 on 2023-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_extension_direct_routing_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='direct_routing_target',
            field=models.CharField(blank=True, help_text='Optional routing target that should be invoked by yate when calling this special number. Calls are routed to the application yate, then stage2 routing invokes this routing target. Format: <pre>"&lt;target&gt;[&semi;&lt;param1&gt;=&lt;value1&gt&semi;&lt;param2&gt;=&lt;value2&gt;…]"</pre> Leave empty if call routing is already handled, e.g., via regexroute.', max_length=256, verbose_name='Yate direct routing target'),
        ),
    ]
