# Generated by Django 4.0.10 on 2023-12-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_extension_direct_routing_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='fourGOptIn',
            field=models.BooleanField(default=True, help_text='Use 4G access technology. Data service quite stable. Voice service depend on your phone.', verbose_name='Use LTE/4G'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='threeGOptIn',
            field=models.BooleanField(default=False, help_text='Use 3G access access technology. Not available at the 37c3.', verbose_name='Use UMTS/3G'),
        ),
    ]
