# Generated by Django 4.0.10 on 2023-12-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_extension_fourgoptin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gsm2G',
            field=models.BooleanField(default=True, verbose_name='2G'),
        ),
        migrations.AddField(
            model_name='event',
            name='gsm3G',
            field=models.BooleanField(default=True, verbose_name='3G'),
        ),
        migrations.AddField(
            model_name='event',
            name='gsm4G',
            field=models.BooleanField(default=True, verbose_name='4G'),
        ),
        migrations.AddField(
            model_name='event',
            name='gsm5G',
            field=models.BooleanField(default=False, verbose_name='5G'),
        ),
    ]
