# Generated by Django 4.0.10 on 2023-12-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_event_gsm2g_event_gsm3g_event_gsm4g_event_gsm5g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='threeGOptIn',
            field=models.BooleanField(default=False, help_text='Use 3G access access technology.', verbose_name='Use UMTS/3G'),
        ),
    ]
