# Generated by Django 4.0.10 on 2024-03-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_extension_threegoptin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='Registration Token')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Token was confirmed')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
