# Generated by Django 4.0.10 on 2024-03-31 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_registrationemailtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemRecallStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_attempt', models.PositiveIntegerField(default=0, verbose_name='Current call attempt')),
                ('next_escalation', models.DateTimeField(verbose_name='Time this extension is next called')),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventorylend', verbose_name='Lending')),
            ],
        ),
    ]
