# Generated by Django 4.1.13 on 2024-06-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_inventoryitemrecallstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="containedIn",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("itemType__isContainer", True)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.inventoryitem",
                verbose_name="Storage container",
            ),
        ),
        migrations.AddField(
            model_name="inventorytype",
            name="isContainer",
            field=models.BooleanField(
                default=False, verbose_name="This item type is a container."
            ),
        ),
    ]
