# Generated by Django 4.1.13 on 2024-06-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_inventoryitem_containedin_inventorytype_iscontainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.event",
                verbose_name="The event that this item is currently used at.",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="containedIn",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("itemType__isContainer", True)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containedItems",
                to="core.inventoryitem",
                verbose_name="Storage container",
            ),
        ),
    ]
