# Generated by Django 2.0.8 on 2018-08-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrandstreamPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, verbose_name='MAC address')),
                ('preSharedPassword', models.CharField(max_length=64, verbose_name='Pre shared password')),
            ],
        ),
    ]
