# Generated by Django 2.0.3 on 2018-08-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandstream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandstreamphone',
            name='adminPassword',
            field=models.CharField(default='eventphone', max_length=64, verbose_name='Admin password'),
        ),
        migrations.AddField(
            model_name='grandstreamphone',
            name='userPassword',
            field=models.CharField(default='eventphone', max_length=64, verbose_name='User password'),
        ),
    ]
