# Generated by Django 2.1.5 on 2019-01-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnomPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, verbose_name='MAC address')),
                ('httpServerPassword', models.CharField(default='eventphone', max_length=64, verbose_name='HTTP server password')),
                ('adminPassword', models.CharField(default='eventphone', max_length=64, verbose_name='Admin password')),
                ('userAgent', models.CharField(max_length=512, null=True, verbose_name='User Agent')),
                ('model', models.CharField(default='', max_length=16, verbose_name='Snom phone model')),
            ],
        ),
    ]
