# Generated by Django 4.0.5 on 2022-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snomphone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
