# Generated by Django 3.0.11 on 2020-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epddi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikrouter',
            name='admin_password',
            field=models.CharField(blank=True, editable=False, max_length=16, verbose_name='Admin User Password'),
        ),
    ]
