# Generated by Django 3.0.11 on 2020-12-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epddi', '0002_mikrotikrouter_admin_password'),
        ('epddi', '0002_epddiclient_vpn_certificate_pem'),
    ]

    operations = [
    ]
