# Generated by Django 3.0.5 on 2020-12-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epddi', '0003_merge_20201217_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='epddiclient',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='The client is currently connected to our VPN'),
        ),
        migrations.AddField(
            model_name='epddiclient',
            name='last_connected',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last connection of this client to our VPN'),
        ),
    ]
