# Generated by Django 3.0.11 on 2020-12-25 01:17

import django.core.validators
from django.db import migrations, models
import epddi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('epddi', '0005_clientcertrevocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epddiclient',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'Mikrotik')], verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='epddiclient',
            name='hostname',
            field=models.CharField(default=epddi.utils.get_new_router_name, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Valid hostnames are alphanumeric plus _ - and .', regex='^[a-zA-Z0-9._-]+$')], verbose_name='Hostname'),
        ),
    ]
